/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
import java.util.regex.PatternSyntaxException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.*;


/**
 *
 * @author HP
 */
public class FormObat extends javax.swing.JFrame {
Statement st ;
private DefaultTableModel tabelModel;
private String kolom[] = {"Kode Obat", "Nama Obat", "Jenis Obat", "Satuan", "Expired", "Harga", "Harga Jual", "Tanggal Masuk", "Jumlah"};
private DefaultTableModel model = new DefaultTableModel(kolom, 0);
    TableRowSorter<TableModel> rowSorter = new TableRowSorter<TableModel>(model);



    /**
     * Creates new form FormObat
     */
    public FormObat() {
        
        initComponents();
       tampilkandata();
       txExpired.setDateFormatString("yyyy-MM-dd");
                txTanggalMasuk.setDateFormatString("yyyy-MM-dd");
       Date date=new Date();
      txExpired.setDate(date);
                txTanggalMasuk.setDate(date);
       
       
    }
    
    
   
    
    
      public Connection conn;
    public void koneksi() throws SQLException {
        try {
            conn=null;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/apotek", "root", "");

        } catch (ClassNotFoundException ex) {
           System.out.println(ex);
        } catch (SQLException e) {
           System.out.println(e);
        } catch (Exception es) {
            System.out.println(es);
        }

    }
    
    
    
    
    
    public void tampilkandata() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("Kode Obat");
        tabelmapel.addColumn("Nama Obat");
        tabelmapel.addColumn("Jenis Obat");
        tabelmapel.addColumn("Satuan");
        tabelmapel.addColumn("Expired");
        tabelmapel.addColumn("Harga");
        tabelmapel.addColumn("Harga Jual");
        tabelmapel.addColumn("Tanggal Masuk");
        tabelmapel.addColumn("Jumlah");
        try {
            koneksi();
            String sql = "select * from obat";
            Statement stat = conn.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                tabelmapel.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),
                res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)
                ,res.getString(9)});
            }
           jTable1.setModel(tabelmapel);
        } catch (Exception e) {
        }

    }
    
    public class CustomTableCellRenderer extends DefaultTableCellRenderer
	{
		public Component getTableCellRendererComponent(JTable tabel, Object obj, boolean isSelected, boolean hasFocus, int baris, int kolom)
		{
			Component comp = super.getTableCellRendererComponent(tabel, obj, isSelected, hasFocus, baris, kolom);
			if(isSelected)
			{
				comp.setBackground(Color.ORANGE);
			}
			else
			{
				comp.setBackground(Color.WHITE);
			}
			
			return comp;
		}
	}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txKdObat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNamaObat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txJenisObat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txSatuan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txExpired = new com.toedter.calendar.JDateChooser();
        txTanggalMasuk = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txHargaJual = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txJumlah = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txCari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apotek Bondan");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Data Obat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("InputData"));

        jLabel2.setText("Kode Obat");

        jLabel3.setText("Nama Obat");

        jLabel4.setText("Jenis Obat");

        txJenisObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJenisObatActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga");

        txHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHargaActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Masuk");

        jLabel7.setText("Satuan");

        txSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSatuanActionPerformed(evt);
            }
        });

        jLabel8.setText("Expired");

        jLabel9.setText("Harga Jual");

        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Simpan");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel10.setText("Jumlah");

        jButton4.setText("Hapus");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Update");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txKdObat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txJenisObat, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(txHarga))))
                .addGap(137, 137, 137)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txHargaJual)
                    .addComponent(txExpired, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txTanggalMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txKdObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(txTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton5)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txJenisObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addComponent(txExpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton1)))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Obat", "Nama Obat", "Jenis Obat", "Harga", "Tanggal Masuk", "Satuan", "Expired", "Harga Jual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCariActionPerformed(evt);
            }
        });

        jLabel11.setText("Pencarian");

        jButton3.setText("Refresh");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCari, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(942, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txJenisObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJenisObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJenisObatActionPerformed

    private void txHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHargaActionPerformed

    private void txSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSatuanActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      
        try {
            
                txExpired.setDateFormatString("yyyy-MM-dd");
                txTanggalMasuk.setDateFormatString("yyyy-MM-dd");
                
                String d1  = ((JTextField)txExpired.getDateEditor().getUiComponent()).getText();
                String d2  = ((JTextField)txTanggalMasuk.getDateEditor().getUiComponent()).getText();
                Connection konek=Koneksi.Koneksi.getKoneksi();
                String query="insert into obat values(?,?,?,?,?,?,?,?,?)";
                
                PreparedStatement state=konek.prepareStatement(query);
                
                state.setString(1, txKdObat.getText());
                state.setString(2, txNamaObat.getText());
                state.setString(3, txJenisObat.getText());
                state.setString(4, txSatuan.getText());
                state.setString(5, d1);
                state.setString(6, txHarga.getText());
                state.setString(7, txHargaJual.getText());
                state.setString(8, d2);
                state.setString(9, txJumlah.getText());
                
                state.executeUpdate();
                System.out.println("Data di simpan");
                txKdObat.setText("");
                txNamaObat.setText("");
                txJenisObat.setText("");
                txSatuan.setText("");
                txHarga.setText("");
                txHargaJual.setText("");
                txJumlah.setText("");
                txExpired.setDate(null);
                txTanggalMasuk.setDate(null);
                state.close();
                tampilkandata();
                
                
                
            } catch (SQLException ex) {
                System.out.println(ex);
                if((txKdObat.getText().length()==0)||
              (txNamaObat.getText().length()==0)||
              (txJenisObat.getText().length()==0)||
              (txSatuan.getText().length()==0)||
              (txHarga.getText().length()==0)||
              (txHargaJual.getText().length()==0)||
              (txJumlah.getText().length()==0)||
              (txExpired.getDate()==null)||
              (txTanggalMasuk.getDate()==null)){
           JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Kesalahan", JOptionPane.ERROR_MESSAGE);

       }else{
                JOptionPane.showMessageDialog(null, "Data Sudah Ada", "Warning!!", JOptionPane.ERROR_MESSAGE);
            }
            }finally{
            txKdObat.setText(null);
            txNamaObat.setText(null);
            txJenisObat.setText(null);
            txSatuan.setText(null);
            txHarga.setText(null);
            txHargaJual.setText(null);
            txJumlah.setText(null);
            
        }
      
            
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        MainForm home=new MainForm();
        home.setVisible(true);
        
        new FormObat();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      try {
          SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
int row = jTable1.rowAtPoint(evt.getPoint());

String a = jTable1.getValueAt(row, 0).toString();
String b = jTable1.getValueAt(row, 1).toString();
String c = jTable1.getValueAt(row, 2).toString();
String d = jTable1.getValueAt(row, 3).toString();
Date e = dateFormat.parse((String)jTable1.getValueAt(jTable1.getSelectedRow(), 4));
String f = jTable1.getValueAt(row, 5).toString();
String g = jTable1.getValueAt(row, 6).toString();
Date h = dateFormat.parse((String)jTable1.getValueAt(jTable1.getSelectedRow(), 7));
String i = jTable1.getValueAt(row, 8).toString();

txKdObat.setText(String.valueOf(a));
txNamaObat.setText(String.valueOf(b));
txJenisObat.setText(String.valueOf(c));
txSatuan.setText(String.valueOf(d));
txExpired.setDate(e);

txHarga.setText(String.valueOf(f));
txHargaJual.setText(String.valueOf(g));
txTanggalMasuk.setDate(h);
txJumlah.setText(String.valueOf(i));
} catch (Exception e) {
    System.out.println(e);
}
				
				
                                
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
    tampilkandata();
    }//GEN-LAST:event_jButton3MouseClicked

    private void txCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCariActionPerformed
      DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("Kode Obat");
        tabelmapel.addColumn("Nama Obat");
        tabelmapel.addColumn("Jenis Obat");
        tabelmapel.addColumn("Satuan");
        tabelmapel.addColumn("Expired");
        tabelmapel.addColumn("Harga");
        tabelmapel.addColumn("Harga Jual");
        tabelmapel.addColumn("Tanggal Masuk");
        tabelmapel.addColumn("Jumlah");
        
        try{
koneksi();
String sql = "Select * from obat where namaObat like '%" + txCari.getText() + "%'" +
"or jenisObat like '%" + txCari.getText() + "%'";
Statement stat = conn.createStatement();
ResultSet rs = stat.executeQuery(sql);
while (rs.next()) {
tabelmapel.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9)
        
});
}
jTable1.setModel(tabelmapel);

}catch (Exception e){
    System.out.println(e);
}
    }//GEN-LAST:event_txCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

    try {
        Connection konek=Koneksi.Koneksi.getKoneksi();
        String query="delete from obat where kodeObat=?";
        PreparedStatement state=konek.prepareStatement(query);
        state.setString(1, txKdObat.getText());
        state.executeUpdate();
        
        System.out.println("Data dihapus");
        tampilkandata();
        state.close();
    } catch (SQLException ex) {
      System.out.println(ex);
    }finally{
        txKdObat.setText("");
            txNamaObat.setText("");
            txJenisObat.setText("");
            txSatuan.setText("");
            txHarga.setText("");
            txHargaJual.setText("");
            txJumlah.setText("");
            txExpired.setDate(null);
            txTanggalMasuk.setDate(null);
    }
    
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
try {
     txExpired.setDateFormatString("yyyy-MM-dd");
                txTanggalMasuk.setDateFormatString("yyyy-MM-dd");
    String d1  = ((JTextField)txExpired.getDateEditor().getUiComponent()).getText();
    String d2  = ((JTextField)txTanggalMasuk.getDateEditor().getUiComponent()).getText();
					Connection konek = Koneksi.Koneksi.getKoneksi();
					String sql = "UPDATE obat SET namaObat = ?, jenisObat = ?, satuanObat= ?, expired= ?,"
                                                + "hargabeli= ?, hargajual= ?, tglMasuk= ?, qty= ? WHERE kodeObat = ?";
					PreparedStatement prepare = konek.prepareStatement(sql);

					prepare.setString(1, txNamaObat.getText());
					prepare.setString(2, txJenisObat.getText());
					prepare.setString(3, txSatuan.getText());
                                        prepare.setString(4, d1);
                                        prepare.setString(5, txHarga.getText());
                                        prepare.setString(6, txHargaJual.getText());
                                        prepare.setString(7, d2);
                                        prepare.setString(8, txJumlah.getText());
                                        prepare.setString(9, txKdObat.getText());

					prepare.executeUpdate();
					JOptionPane.showMessageDialog(null, "Data berhasil diubah");
					tampilkandata();
					prepare.close();
				} catch (Exception ex) {
					JOptionPane.showMessageDialog(null, "Data gagal diubah");
                                        System.out.println(ex);
				}

				finally {
					txKdObat.setText("");
            txNamaObat.setText("");
            txJenisObat.setText("");
            txSatuan.setText("");
            txHarga.setText("");
            txHargaJual.setText("");
            txJumlah.setText("");
            txExpired.setDate(null);
            txTanggalMasuk.setDate(null);
				}       
    }//GEN-LAST:event_jButton5MouseClicked

    
   
    
    
    
    
    
    
    public void tampilTabel() {
        
		
		tabelModel.getDataVector().removeAllElements();
		tabelModel.fireTableDataChanged();
		try {
			Connection konek = Koneksi.Koneksi.getKoneksi();
			Statement state = konek.createStatement();
			String sql = "SELECT * FROM obat";

			ResultSet rs = state.executeQuery(sql);
			while (rs.next()) {
				Object obj[] = new Object[9];
				obj[0] = rs.getString(1);
				obj[1] = rs.getString(2);
				obj[2] = rs.getString(3);
                                obj[3] = rs.getString(4);
				obj[4] = rs.getString(5);
				obj[5] = rs.getString(6);
                                obj[6] = rs.getString(7);
				obj[7] = rs.getString(8);
				obj[8] = rs.getString(8);

				tabelModel.addRow(obj);
			}

			rs.close();
			state.close();
		} catch (Exception ex) {
			System.out.println(ex);
		}
	}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txCari;
    private com.toedter.calendar.JDateChooser txExpired;
    private javax.swing.JTextField txHarga;
    private javax.swing.JTextField txHargaJual;
    private javax.swing.JTextField txJenisObat;
    private javax.swing.JTextField txJumlah;
    private javax.swing.JTextField txKdObat;
    private javax.swing.JTextField txNamaObat;
    private javax.swing.JTextField txSatuan;
    private com.toedter.calendar.JDateChooser txTanggalMasuk;
    // End of variables declaration//GEN-END:variables
}
