/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Pembelian extends javax.swing.JFrame {
DefaultComboBoxModel model, model2;
private String KodeSupplier, KodeObat;
    /**
     * Creates new form Pembelian
     */
    public Pembelian() {
        initComponents();
        setModel();
        cmbSup.setModel(model);
        setModel2();
       cmbObat.setModel(model2);
        tampilkandata();
    }
    
    
    private void setKodeSupplier(String KodeSupplier){
        this.KodeSupplier=KodeSupplier;
    }
    
    private String getKodeSupplier(){
        return KodeSupplier;
    }
    
    
    private void setKodeObat(String KodeObat){
        this.KodeObat=KodeObat;
    }
    
    private String getKodeObat(){
        return KodeObat;
    }
    
    
    
    public Connection conn;
    public void koneksi() throws SQLException {
        try {
            conn=null;
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/apotek", "root", "");

        } catch (ClassNotFoundException ex) {
           System.out.println(ex);
        } catch (SQLException e) {
           System.out.println(e);
        } catch (Exception es) {
            System.out.println(es);
        }

    }
    
    
    
    public void tampilkandata() {
        DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("No Faktur");
        tabelmapel.addColumn("Tanggal Transaksi");    
         tabelmapel.addColumn("Kode Supplier");
          tabelmapel.addColumn("Nama Supplier");
        tabelmapel.addColumn("Kode Obat");      
        tabelmapel.addColumn("Nama Obat");      
        tabelmapel.addColumn("Harga");

        tabelmapel.addColumn("Jumlah");
        
        try {
            koneksi();
            String sql = "select pembelian.noFakturBeli, pembelian.tgltransaksi, "
                    + "supplier.kodeSupplier, supplier.namaSupplier, obat.kodeObat, "
                    + "obat.namaObat, pembelian.harga, pembelian.qty from pembelian join supplier "
                    + "on pembelian.kodeSupplier=supplier.kodeSupplier join obat "
                    + "on pembelian.kodeObat=obat.kodeObat";
            Statement stat = conn.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                tabelmapel.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),
                res.getString(4),res.getString(5), res.getString(6),res.getString(7),res.getString(8)});
            }
           jTable1.setModel(tabelmapel);
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txFaktur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txJumlah = new javax.swing.JTextField();
        dtTgl = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbSup = new javax.swing.JComboBox();
        cmbObat = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txCari = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apotek Bondan");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Data Pembelian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data"));

        jLabel2.setText("No Faktur Beli");

        jLabel3.setText("Supplier");

        jLabel4.setText("Harga");

        jLabel5.setText("Tanggal Transaksi");

        jLabel6.setText("Nama Obat");

        jLabel7.setText("Jumlah");

        jButton1.setText("Simpan");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Home");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        cmbSup.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbSupPopupMenuWillBecomeVisible(evt);
            }
        });
        cmbSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupActionPerformed(evt);
            }
        });

        cmbObat.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbObatPopupMenuWillBecomeVisible(evt);
            }
        });
        cmbObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbObatActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txHarga, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbObat, javax.swing.GroupLayout.Alignment.LEADING, 0, 118, Short.MAX_VALUE)
                            .addComponent(cmbSup, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txJumlah)
                            .addComponent(dtTgl, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbSup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addComponent(dtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(21, 21, 21))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No Faktur Beli", "Kode Supplier", "Harga", "Kode Obat", "Jumlah", "Tanggal Transaksi"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("Pencarian : ");

        txCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCariActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txCari, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(699, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    MainForm main=new MainForm();
    main.setVisible(true);
    
    Pembelian beli=new Pembelian();
    setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void cmbSupPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbSupPopupMenuWillBecomeVisible
    cmbSup.removeAllItems();
       Statement statement=null;
       ResultSet resultSet=null;
       
       try{ 
          statement = Koneksi.DatabaseHelper.getConnection().createStatement();
	    resultSet = statement.executeQuery("select namaSupplier from supplier");
	    while (resultSet.next()) {
		String obat = resultSet.getString("namaSupplier");
		cmbSup.addItem(obat);
	    }
	} catch (SQLException ex) {
            System.out.println(ex);
	} finally {
	    try {
		if (resultSet != null) {
		    resultSet.close();
		}
	    } catch (SQLException ex) {
                System.out.println(ex);
	    }
	    try {
		if (statement != null) {
		    statement.close();
		}
	    } catch (SQLException ex) {
                System.out.println(ex);
	    }
	}
    }//GEN-LAST:event_cmbSupPopupMenuWillBecomeVisible

    private void cmbSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupActionPerformed
      if(cmbSup.getSelectedItem()!=null){
          try {
              String query="select kodeSupplier from supplier where namaSupplier=?";
              PreparedStatement state=Koneksi.Koneksi.getKoneksi().prepareStatement(query);
              state.setString(1, cmbSup.getSelectedItem().toString());
              ResultSet res=state.executeQuery();
              while(res.next()){
                  this.setKodeSupplier(res.getString(1));
              }
          } catch (SQLException ex) {
              
          }
      }
    }//GEN-LAST:event_cmbSupActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    try {
        
            dtTgl.setDateFormatString("yyyy-MM-dd");
    String d1  = ((JTextField)dtTgl.getDateEditor().getUiComponent()).getText();
            Connection konek=Koneksi.Koneksi.getKoneksi();
            String query="insert into pembelian values(?, ?, ?, ?, ?, ?)";
            PreparedStatement state=konek.prepareStatement(query);
            state.setString(1, txFaktur.getText());
            state.setString(2, d1);
             state.setString(3, this.getKodeSupplier());
            state.setString(4, this.getKodeObat());
            state.setString(5, txHarga.getText());
            state.setString(6, txJumlah.getText());
           
            state.executeUpdate();
            System.out.println("Data disimpan");
            state.close();
            tampilkandata();
        } catch (SQLException ex) {
            System.out.println(ex);
            if((txFaktur.getText().length()==0)||
                    (txHarga.getText().length()==0)||
                    (txJumlah.getText().length()==0)){
                JOptionPane.showMessageDialog(null, "Data Harus Diisi Semua", "Warning!!", JOptionPane.WARNING_MESSAGE);
                
            }else{
                            JOptionPane.showMessageDialog(null, "Data Sudah Ada", "Warning!!", JOptionPane.ERROR_MESSAGE);
            }
        }finally{
            txFaktur.setText("");
            txJumlah.setText("");
            dtTgl.setDate(null);
            txHarga.setText("");
         
        }
   
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
        Connection konek=Koneksi.Koneksi.getKoneksi();
        String query="delete from pembelian where noFakturBeli=?";
        PreparedStatement state=konek.prepareStatement(query);
        state.setString(1, txFaktur.getText());
        state.executeUpdate();
        
        System.out.println("Data dihapus");
        tampilkandata();
        state.close();
    } catch (SQLException ex) {
      System.out.println(ex);
    }finally{
        txFaktur.setText("");
            txJumlah.setText("");
            txHarga.setText("");
            dtTgl.setDate(null);
            
    }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     try {
          SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
int row = jTable1.rowAtPoint(evt.getPoint());

String a = jTable1.getValueAt(row, 0).toString();
Date b = dateFormat.parse((String)jTable1.getValueAt(jTable1.getSelectedRow(), 1));
String x = jTable1.getValueAt(row,3).toString();
String c = jTable1.getValueAt(row, 6).toString();
String d = jTable1.getValueAt(row, 7).toString();




txFaktur.setText(String.valueOf(a));
dtTgl.setDate(b);
txHarga.setText(String.valueOf(c));
txJumlah.setText(String.valueOf(d));


} catch (Exception e) {
    System.out.println(e);
}
     
     
     
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void txCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCariActionPerformed
     DefaultTableModel tabelmapel = new DefaultTableModel();
        tabelmapel.addColumn("No Faktur");
        tabelmapel.addColumn("Tanggal Transaksi");    
         tabelmapel.addColumn("Kode Supplier");
          tabelmapel.addColumn("Nama Supplier");
        tabelmapel.addColumn("Kode Obat"); 
        tabelmapel.addColumn("Nama Obat"); 
        tabelmapel.addColumn("Harga");

        tabelmapel.addColumn("Jumlah");
        
        try{
koneksi();
String sql = "Select pembelian.noFakturBeli, pembelian.tglTransaksi, supplier.kodeSupplier ,supplier.namaSupplier, obat.kodeObat, obat.namaObat, pembelian.harga, pembelian.qty from pembelian join supplier on pembelian.kodeSupplier=supplier.kodeSupplier "
        + "join obat on pembelian.kodeObat=obat.kodeObat where "
        + "pembelian.noFakturBeli like '%" + txCari.getText() + "%'" 
        + "or pembelian.tglTransaksi like '%" + txCari.getText() + "%'"
        + "or obat.kodeObat like '%" + txCari.getText() + "%'"
        + "or supplier.kodeSupplier like '%" + txCari.getText() + "%'"
        + "or supplier.namaSupplier like '%" + txCari.getText() + "%'"
        + "or obat.namaObat like '%" + txCari.getText() + "%'";
Statement stat = conn.createStatement();
ResultSet rs = stat.executeQuery(sql);
while (rs.next()) {
tabelmapel.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),

        
});
}
jTable1.setModel(tabelmapel);

}catch (Exception e){
    System.out.println(e);
}
    }//GEN-LAST:event_txCariActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
     tampilkandata();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int qty=0;
        try{
         
                qty=cekStok()-Integer.parseInt(txJumlah.getText());
           
            String query="update obat set qty='"+qty+"'where kodeObat='"+getKodeObat()+"'";
            Statement state=Koneksi.Koneksi.getKoneksi().createStatement();
            state.executeUpdate(query);
        }catch(Exception e){
        System.out.println(e);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbObatActionPerformed
        if(cmbObat.getSelectedItem()!=null){
            try {
                String query="select kodeObat from obat where namaObat=?";
                PreparedStatement state=Koneksi.Koneksi.getKoneksi().prepareStatement(query);
                state.setString(1, cmbObat.getSelectedItem().toString());
                ResultSet res=state.executeQuery();
                while(res.next()){
                    this.setKodeObat(res.getString(1));
                }
            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_cmbObatActionPerformed

    private void cmbObatPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbObatPopupMenuWillBecomeVisible
        cmbObat.removeAllItems();
        Statement statement=null;
        ResultSet resultSet=null;

        try{
            statement = Koneksi.DatabaseHelper.getConnection().createStatement();
            resultSet = statement.executeQuery("select namaSupplier from supplier");
            while (resultSet.next()) {
                String obat = resultSet.getString("namaSupplier");
                cmbObat.addItem(obat);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            try {
                if (resultSet != null) {
                    resultSet.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            try {
                if (statement != null) {
                    statement.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_cmbObatPopupMenuWillBecomeVisible

    private int cekStok(){
        int stok=0;
        String query="select qty from obat where kodeObat='"+getKodeObat()+"'";
        try{
            Statement state=Koneksi.Koneksi.getKoneksi().createStatement();
            ResultSet res=state.executeQuery(query);
            while(res.next()){
                stok=Integer.parseInt(res.getString(1));
            }
        }catch(Exception x){
            System.out.println(x);
        }
        return stok;
    }
    /*
    private void updateQty(String ubah){
        int qty=0;
        try{
            if(ubah.equals("simpan")){
                qty=cekStok()+Integer.parseInt(txJumlah.getText());
            }
            String query="update obat set qty='"+qty+"'where kodeObat='"+this.getKodeObat()+"'";
            Statement state=Koneksi.Koneksi.getKoneksi().createStatement();
            state.executeUpdate(query);
        }catch(Exception e){
        System.out.println(e);
    }
    }
    
    */
    
    public void setModel(){
        try{
            PreparedStatement state=Koneksi.Koneksi.getKoneksi().prepareStatement("select namaSupplier from supplier");
            ResultSet res=state.executeQuery();
            model=new DefaultComboBoxModel();
            while(res.next()){
                model.addElement(res.getString(1));
            }
            
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    
    public void setModel2(){
        try{
            PreparedStatement state=Koneksi.Koneksi.getKoneksi().prepareStatement("select namaObat from obat");
            ResultSet res=state.executeQuery();
            model2=new DefaultComboBoxModel();
            while(res.next()){
                model2.addElement(res.getString(1));
            }
            
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbObat;
    private javax.swing.JComboBox cmbSup;
    private com.toedter.calendar.JDateChooser dtTgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txCari;
    private javax.swing.JTextField txFaktur;
    private javax.swing.JTextField txHarga;
    private javax.swing.JTextField txJumlah;
    // End of variables declaration//GEN-END:variables
}
